---
stages:
  - acceptance

default-test:
  stage: acceptance
  tags:
    - beaker
  script:
    - rm Gemfile.lock || true
    - bundle install --no-binstubs --path=vendor
    - bundle exec rake beaker:suites[default]

rpm_el6-test:
  stage: acceptance
  tags:
    - beaker
  script:
    - rm Gemfile.lock || true
    - bundle install --no-binstubs --path=vendor
    - bundle exec rake beaker:suites[rpm_el6]

rpm_el7-test:
  stage: acceptance
  tags:
    - beaker
  script:
    - rm Gemfile.lock || true
    - bundle install --no-binstubs --path=vendor
    - bundle exec rake beaker:suites[rpm_el7]

kubernetes-test:
  stage: acceptance
  tags:
    - beaker
  script:
    - rm Gemfile.lock || true
    - bundle install --no-binstubs --path=vendor
    - bundle exec rake beaker:suites[kubernetes]

forge_install-test:
  stage: acceptance
  tags:
    - beaker
  script:
    - rm Gemfile.lock || true
    - bundle install --no-binstubs --path=vendor
    - bundle exec rake beaker:suites[forge_install]

# Just gonna comment this one out for now...
# acceptance-rpm_docker:
#   stage: acceptance
#   tags:
#     - beaker
#   script:
#     - rm Gemfile.lock || true
#     - bundle install --no-binstubs --path=vendor
#     - bundle exec rake beaker:suites[rpm_docker]
