HOSTS:
  puppet:
    roles:
      - server # Mandatory
      - master
      - default
      - simp_server
    platform:   el-7-x86_64
    box:        centos/7
    hypervisor: vagrant
    vagrant_memsize: 4608
    vagrant_cpus: 2
  kube-master01:
    roles:
      - agent
      - kube-master
    platform:   el-7-x86_64
    box:        centos/7
    hypervisor: vagrant
    vagrant_memsize: 1024
    vagrant_cpus: 2
  kube-node01:
    roles:
      - agent
      - kube-node
    platform:   el-7-x86_64
    box:        centos/7
    hypervisor: vagrant
  kube-node02:
    roles:
      - agent
      - kube-node
    platform:   el-7-x86_64
    box:        centos/7
    hypervisor: vagrant
CONFIG:
  log_level: verbose
  type:      aio
  vagrant_memsize: 512
  synced_folder: disabled
  # vb_gui: true
