---
# This folder will be populated by running the `simp config` command.
#
# This is the default cli hiera file
# Any parameters added here will be applied to every system as defined by the
# hostgroup variable
#
# Hiera crashes if there are empty files, so
# please remove the following line if you use this file
this_is_another_example_key: 'that does nothing'
