HOSTS:
  puppet:
    roles:
      - server
      - master
      - ipa-client
      - agent
    platform:   el-7-x86_64
    box:        centos/7
    hypervisor: vagrant
    vagrant_memsize: 4608
    vagrant_cpus: 2

  ipa:
    roles:
      - ipa-server
      - agent
    masterless: true
    platform:   el-7-x86_64
    box:        centos/7
    hypervisor: vagrant
    # IPA needs more resources than those used in a typical module acceptance test
    vagrant_memsize: 2048
    vagrant_cpus: 2
    forwarded_ports:
      ipa:
        from: 7443
        to: 443

  el7-client:
    roles:
      - ipa-client
      - agent
    masterless: true
    platform:   el-7-x86_64
    box:        centos/7
    hypervisor: vagrant

  el6-client:
    roles:
      - ipa-client
      - agent
      - no_fips
    masterless: true
    platform:   el-6-x86_64
    box:        centos/6
    hypervisor: vagrant

CONFIG:
  log_level: verbose
  type:      aio
  vagrant_memsize: 256
  vagrant_cpus: 1
